name: 'technical-test'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cheil_peru
    ports:
      - '5432:5432'
  backend:
    image: node:22.6.0-bullseye
    ports:
      - '3001:3000'
    depends_on:
      - database
  frontend:
    image: node:22.6.0-bullseye
    ports:
      - '3000:3000'
    depends_on:
      - backend
