name: 'fullstack-app'

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cheil_peru
    ports:
      - '5432:5432'
  backend:
    image: node:22.6.0-bullseye
    environment:
      DATABASE_URL: postgres://postgres:mysecret@database:5432/cheil_peru
    volumes:
      - ./backend:/app
    ports:
      - '3001:3000'
    depends_on:
      - database
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run start:dev"
  frontend:
    image: node:22.6.0-bullseye
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
