name: 'fullstack-app'

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cheil_peru
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:mysecret@database:5432/cheil_peru
    volumes:
      - ./backend:/app
    ports:
      - '3001:3000'
    depends_on:
      - database
    command: npm run start:dev
